# Generated by Django 5.0.7 on 2024-09-17 18:49

import apps.base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, help_text='Введите телефонный номер в международном формате', max_length=16, validators=[apps.base.validators.validation_phone], verbose_name='Телефонный номер'),
        ),
    ]
