# Generated by Django 5.0.7 on 2024-10-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_confirmed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_confirmed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
