# Generated by Django 5.0.7 on 2024-09-18 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Пользователь с таким адресом электронной почты уже существует.'}, max_length=254, unique=True, verbose_name='адрес электронной почты'),
        ),
    ]
