# Generated by Django 5.0.7 on 2024-09-24 21:58

import apps.base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким номером телефона уже существует.'}, help_text='Введите телефонный номер в международном формате', max_length=16, unique=True, validators=[apps.base.validators.validation_phone], verbose_name='Телефонный номер'),
        ),
    ]
