# Generated by Django 5.0.7 on 2024-10-27 15:44

import apps.users.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', apps.users.managers.CustomUserManager()),
            ],
        ),
    ]
