# Generated by Django 5.0.7 on 2024-10-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='key',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
