# Generated by Django 5.0.7 on 2024-10-14 19:21

import apps.base.services
import apps.base.validators
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название категории (макс. 100 символов)', max_length=100, verbose_name='Название категории')),
                ('icon', models.ImageField(help_text='Загрузите иконку в формате PNG. Размер файла не должен превышать установленный лимит 0.5MB.', upload_to='icons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'], message='Разрешен только формат PNG'), apps.base.validators.FileSizeValidator()], verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'категорию',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название продукта (макс. 100 символов)', max_length=100, verbose_name='Название товара')),
                ('description', models.TextField(help_text='Введите описание продукта (макс. 400 символов)', max_length=400, verbose_name='Описание')),
                ('price', models.PositiveIntegerField(help_text='Укажите цену продукта', verbose_name='Цена')),
                ('currency', models.CharField(choices=[('KGS', 'СОМ'), ('USD', 'ДОЛЛАР')], help_text='Выберите валюту для цены продукта', max_length=3, verbose_name='Валюта')),
                ('product_rating', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Оценка от 0.00 до 5.00', max_digits=3, validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(0.0)], verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
        migrations.CreateModel(
            name='ProductFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(help_text='Загрузите изображение продукта', upload_to=apps.base.services.path_photo_product, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), apps.base.validators.FileSizeValidator(max_size_mb=1.2)], verbose_name='Фото продукта')),
            ],
            options={
                'verbose_name': 'фото продукта',
                'verbose_name_plural': 'фотографии продуктов',
            },
        ),
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_rating', models.PositiveSmallIntegerField(help_text='Оценка магазина от 1 до 5', validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Оценка')),
                ('comment', models.CharField(blank=True, max_length=150, null=True, verbose_name='Комментарии для магазина')),
                ('date_writing', models.DateTimeField(auto_now_add=True, help_text='Дата и время написания отзыва', verbose_name='Дата написания')),
                ('update_to', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления отзыва', verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'рейтинг',
                'verbose_name_plural': 'рейтинги',
            },
        ),
        migrations.CreateModel(
            name='ProposalNewCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Введите ваше предложение для новой категории (макс. 700 символов)', max_length=700, verbose_name='Предложение')),
            ],
            options={
                'verbose_name': 'предложение',
                'verbose_name_plural': 'предложении',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название подкатегории (макс. 100 символов)', max_length=100, verbose_name='Название подкатегории')),
                ('icon', models.ImageField(help_text='Загрузите иконку в формате PNG. Размер файла не должен превышать установленный лимит 0.5MB.', upload_to='icons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'], message='Разрешен только формат PNG'), apps.base.validators.FileSizeValidator()], verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'подкатегорию',
                'verbose_name_plural': 'подкатегории',
            },
        ),
    ]
