# Generated by Django 5.0 on 2024-10-07 05:38

import apps.base.services
import apps.base.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0010_alter_complaint_screenshot_alter_shop_background_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название категории (макс. 100 символов)', max_length=100, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название продукта (макс. 100 символов)', max_length=100, verbose_name='Название продукта')),
                ('description', models.TextField(help_text='Введите описание продукта (макс. 400 символов)', max_length=400, verbose_name='Описание')),
                ('price', models.PositiveIntegerField(help_text='Укажите цену продукта', verbose_name='Цена')),
                ('currency', models.CharField(choices=[('KGS', 'СОМ'), ('USD', 'ДОЛЛАР')], help_text='Выберите валюту для цены продукта', max_length=3, verbose_name='Валюта')),
                ('shop', models.OneToOneField(help_text='Укажите магазин, в котором продается продукт', on_delete=django.db.models.deletion.PROTECT, to='shops.shop', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='ProductFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(help_text='Загрузите изображение продукта', upload_to=apps.base.services.path_photo_product, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), apps.base.validators.validate_foto_size_product], verbose_name='Фото продукта')),
                ('product', models.ForeignKey(help_text='Выберите продукт, к которому относится фото', on_delete=django.db.models.deletion.CASCADE, to='goods.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Фото продукта',
                'verbose_name_plural': 'Фотографии продуктов',
            },
        ),
        migrations.CreateModel(
            name='ProposalNewCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Введите ваше предложение для новой категории (макс. 700 символов)', max_length=700, verbose_name='Предложение новой категории')),
                ('user', models.ForeignKey(help_text='Выберите пользователя, сделавшего предложение', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Предложение новой категории',
                'verbose_name_plural': 'Предложения новых категорий',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название подкатегории (макс. 100 символов)', max_length=100, verbose_name='Название подкатегории')),
                ('category', models.ForeignKey(help_text='Выберите категорию для подкатегории', on_delete=django.db.models.deletion.CASCADE, to='goods.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='Выберите подкатегорию продукта', on_delete=django.db.models.deletion.PROTECT, to='goods.subcategory', verbose_name='Подкатегория'),
        ),
    ]
