# Generated by Django 5.0 on 2024-10-07 15:47

import apps.base.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категорию', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'подкатегорию', 'verbose_name_plural': 'подкатегории'},
        ),
        migrations.AddField(
            model_name='proposalnewcategory',
            name='icon',
            field=models.ImageField(default=1, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png']), apps.base.validators.validate_file_size_avatar]),
            preserve_default=False,
        ),
    ]
