# Generated by Django 5.0.7 on 2024-10-14 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.OneToOneField(help_text='Укажите магазин, в котором продается продукт', on_delete=django.db.models.deletion.PROTECT, to='shops.shop', verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='productfoto',
            name='product',
            field=models.ForeignKey(help_text='Выберите продукт, к которому относится фото', on_delete=django.db.models.deletion.CASCADE, to='goods.product', verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='productrating',
            name='product',
            field=models.ForeignKey(help_text='Магазин, который был оценен', on_delete=django.db.models.deletion.CASCADE, to='goods.product', verbose_name='Магазин'),
        ),
    ]
