# Generated by Django 5.0 on 2024-10-07 15:50

import apps.base.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_category_options_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalnewcategory',
            name='icon',
            field=models.ImageField(help_text='Загрузите иконку в формате PNG. Размер файла не должен превышать установленный лимит 0.5MB.', upload_to='icons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'], message='Разрешен только формат PNG'), apps.base.validators.validate_file_size_avatar], verbose_name='Иконка'),
        ),
    ]
