# Generated by Django 5.0.7 on 2024-10-14 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='user',
            field=models.ForeignKey(help_text='Пользователь, оставивший оценку', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='proposalnewcategory',
            name='user',
            field=models.ForeignKey(help_text='Выберите пользователя, сделавшего предложение', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(help_text='Выберите категорию для подкатегории', on_delete=django.db.models.deletion.CASCADE, to='goods.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='Выберите подкатегорию продукта', on_delete=django.db.models.deletion.PROTECT, to='goods.subcategory', verbose_name='Подкатегория'),
        ),
        migrations.AlterUniqueTogether(
            name='productrating',
            unique_together={('user', 'product')},
        ),
    ]
