# Generated by Django 5.0 on 2024-10-07 15:58

import apps.base.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_proposalnewcategory_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposalnewcategory',
            options={'verbose_name': 'предложение', 'verbose_name_plural': 'предложении'},
        ),
        migrations.RemoveField(
            model_name='proposalnewcategory',
            name='icon',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='icon',
            field=models.ImageField(default=1, help_text='Загрузите иконку в формате PNG. Размер файла не должен превышать установленный лимит 0.5MB.', upload_to='icons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'], message='Разрешен только формат PNG'), apps.base.validators.validate_file_size_avatar], verbose_name='Иконка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proposalnewcategory',
            name='text',
            field=models.TextField(help_text='Введите ваше предложение для новой категории (макс. 700 символов)', max_length=700, verbose_name='Предложение'),
        ),
    ]
