# Generated by Django 5.0 on 2024-10-07 16:00

import apps.base.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_alter_proposalnewcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(default=1, help_text='Загрузите иконку в формате PNG. Размер файла не должен превышать установленный лимит 0.5MB.', upload_to='icons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'], message='Разрешен только формат PNG'), apps.base.validators.validate_file_size_avatar], verbose_name='Иконка'),
            preserve_default=False,
        ),
    ]
