# Generated by Django 5.0 on 2024-10-08 00:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_category_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
        migrations.AlterModelOptions(
            name='productfoto',
            options={'verbose_name': 'фото продукта', 'verbose_name_plural': 'фотографии продуктов'},
        ),
        migrations.AddField(
            model_name='product',
            name='product_rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Оценка от 0.00 до 5.00', max_digits=3, validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(0.0)], verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(help_text='Введите название продукта (макс. 100 символов)', max_length=100, verbose_name='Название товара'),
        ),
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_rating', models.PositiveSmallIntegerField(help_text='Оценка магазина от 1 до 5', validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Оценка')),
                ('comment', models.CharField(blank=True, max_length=150, null=True, verbose_name='Комментарии для магазина')),
                ('date_writing', models.DateTimeField(auto_now_add=True, help_text='Дата и время написания отзыва', verbose_name='Дата написания')),
                ('update_to', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления отзыва', verbose_name='Дата обновления')),
                ('product', models.ForeignKey(help_text='Магазин, который был оценен', on_delete=django.db.models.deletion.CASCADE, to='goods.product', verbose_name='Магазин')),
                ('user', models.ForeignKey(help_text='Пользователь, оставивший оценку', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'рейтинг',
                'verbose_name_plural': 'рейтинги',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
