# Generated by Django 5.0.7 on 2024-11-17 20:12

import apps.base.services
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=apps.base.services.path_image_message, validators=[apps.base.services.FileSizeValidator(max_size_mb=1.5), django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'pdf', 'docs', 'xls', 'xlsx', 'pptx'])])),
                ('is_read', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
