# Generated by Django 5.0 on 2024-10-08 00:59

import apps.base.services
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0006_alter_product_options_alter_productfoto_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_to', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания чата', verbose_name='Дата создания')),
                ('product', models.ForeignKey(help_text='Продукт, связанный с чатом', on_delete=django.db.models.deletion.PROTECT, to='goods.product', verbose_name='Продукт')),
                ('product_rating', models.ForeignKey(blank=True, help_text='Оценка продукта, если применимо', null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.productrating', verbose_name='Оценка продукта')),
                ('seller', models.ForeignKey(help_text='Пользователь, который продает товар', on_delete=django.db.models.deletion.PROTECT, related_name='chats_received', to=settings.AUTH_USER_MODEL, verbose_name='Продавец')),
                ('user', models.ForeignKey(help_text='Обычный пользователь', on_delete=django.db.models.deletion.PROTECT, related_name='chats_sent', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
                'ordering': ['-create_to'],
                'unique_together': {('user', 'seller')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, help_text='Текст сообщения (макс. 300 символов)', max_length=300, null=True, verbose_name='Сообщение')),
                ('image', models.ImageField(blank=True, help_text='Изображение в формате JPG или PNG', null=True, upload_to=apps.base.services.path_image_message, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])], verbose_name='Изображение')),
                ('file', models.FileField(blank=True, help_text='Файл документа (DOCX, PDF, TXT)', null=True, upload_to=apps.base.services.path_file_message, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx', 'pdf', 'txt'])], verbose_name='Файл')),
                ('create_to', models.DateTimeField(auto_now_add=True, help_text='Дата и время отправки сообщения', verbose_name='Дата отправки')),
                ('is_read', models.BooleanField(blank=True, default=False, help_text='Отметьте, если сообщение было прочитано', verbose_name='Прочитано')),
                ('chat', models.ForeignKey(help_text='Чат, к которому относится сообщение', on_delete=django.db.models.deletion.PROTECT, to='chats.chat', verbose_name='Чат')),
                ('sender', models.ForeignKey(help_text='Пользователь, получивший сообщение', on_delete=django.db.models.deletion.PROTECT, related_name='messages_received', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('user', models.ForeignKey(help_text='Пользователь, отправивший сообщение', on_delete=django.db.models.deletion.PROTECT, related_name='messages_sent', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-create_to'],
            },
        ),
    ]
