# Generated by Django 5.0.7 on 2024-10-14 19:21

import apps.base.services
import apps.base.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_to', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания чата', verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'чат',
                'verbose_name_plural': 'чаты',
                'ordering': ['-create_to'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, help_text='Текст сообщения (макс. 300 символов)', max_length=300, null=True, verbose_name='Сообщение')),
                ('image', models.ImageField(blank=True, help_text='Изображение в формате JPG или PNG', null=True, upload_to=apps.base.services.path_image_message, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), apps.base.validators.FileSizeValidator()], verbose_name='Изображение')),
                ('file', models.FileField(blank=True, help_text='Файл документа (DOCX, PDF, TXT)', null=True, upload_to=apps.base.services.path_file_message, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx', 'pdf', 'txt']), apps.base.validators.FileSizeValidator(max_size_mb=5)], verbose_name='Файл')),
                ('create_to', models.DateTimeField(auto_now_add=True, help_text='Дата и время отправки сообщения', verbose_name='Дата отправки')),
                ('is_read', models.BooleanField(blank=True, default=False, help_text='Отметьте, если сообщение было прочитано', verbose_name='Прочитано')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
                'ordering': ['-create_to'],
            },
        ),
    ]
