# Generated by Django 5.0.7 on 2024-10-14 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='product',
            field=models.ForeignKey(help_text='Продукт, связанный с чатом', on_delete=django.db.models.deletion.PROTECT, to='goods.product', verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='chat',
            name='product_rating',
            field=models.ForeignKey(blank=True, help_text='Оценка продукта, если применимо', null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.productrating', verbose_name='Оценка продукта'),
        ),
    ]
