# Generated by Django 5.0.7 on 2024-10-14 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='seller',
            field=models.ForeignKey(help_text='Пользователь, который продает товар', on_delete=django.db.models.deletion.PROTECT, related_name='chats_received', to=settings.AUTH_USER_MODEL, verbose_name='Продавец'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(help_text='Обычный пользователь', on_delete=django.db.models.deletion.PROTECT, related_name='chats_sent', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(help_text='Чат, к которому относится сообщение', on_delete=django.db.models.deletion.PROTECT, to='chats.chat', verbose_name='Чат'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(help_text='Пользователь, отправивший сообщение', on_delete=django.db.models.deletion.PROTECT, related_name='messages_sent', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('user', 'seller')},
        ),
    ]
