# Generated by Django 5.0.7 on 2024-10-14 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_alter_chat_unique_together_chat_users_and_more'),
        ('goods', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Продукт, связанный с чатом', null=True, on_delete=django.db.models.deletion.PROTECT, to='goods.product', verbose_name='Продукт'),
        ),
    ]
