stages:
  - build
  - test
  - deploy

build-all:
  stage: build
  script:
    - cp .env.example .env.db
    - cp .env.example .env.dev
    - docker compose --profile all down
    - docker compose --profile all build

test-api-1:
  stage: test
  script:
    - sleep 20
    - echo "Test"
  only:
    - merge_requests

deploy-prod:
  stage: deploy
  only:
    - main
  script:
    - docker compose --profile all up -d --build
