stages:
  - build
  - test
  - deploy

build-all:
  stage: build
  script:
    - cp .env.example .env.db
    - cp .env.example .env.dev
    - docker compose --profile all down
    - docker compose --profile all build
  only:
    - merge_requests

test-api-1:
  needs:
    - build-all
  stage: test
  script:
    - sleep 20
    - echo "Test"
  only:
    - merge_requests

deploy-prod:
  stage: deploy
  environment: production
  only:
    - main
  script:
    - cp $DJANGO_ENV_FILE .env.db
    - cp $POSTGRES_ENV_FILE .env.dev
    - docker compose --profile all up -d --build
