
services:
  db:
    container_name: db-postgres
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    profiles:
      - all

  api: &default-django
    container_name: api-django
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - media:/code/media
      - static:/code/static
    entrypoint: /code/wsgi-entrypoint.sh
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - .env
    profiles:
      - all
      - dev

  celery: &default-celery
    <<: *default-django
    container_name: celery-django
    command: "celery -A config worker -l info"
    depends_on:
      - api
    entrypoint: []
    ports: []

#  web:
#    container_name: web-react
#    build: ./frontend
#    ports:
#     - "3000:3000"
#    restart: always
#    command: npm start
#    profiles:
#        - all
#    networks:
#      dev:

  nginx:
    container_name: nginx
    build: ./nginx
    depends_on:
      - api
#      - web
    ports:
      - "80:80"
    volumes:
      - media:/media
      - static:/static
    profiles:
      - all

volumes:
  postgres_data:
  media:
  static:
