# Generated by Django 5.0.7 on 2024-11-17 20:12

import apps.base.services
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=1500)),
                ('logo', models.ImageField(upload_to=apps.base.services.path_logo_shop, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), apps.base.services.FileSizeValidator(max_size_mb=3)])),
                ('background', models.ImageField(upload_to=apps.base.services.path_background_shop, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), apps.base.services.FileSizeValidator(max_size_mb=3)])),
                ('address', models.URLField()),
                ('indicate_address', models.BooleanField(blank=True, default=True)),
                ('number_of_complaints', models.PositiveIntegerField(blank=True, default=0)),
                ('link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(1.0)])),
            ],
        ),
    ]
