# Generated by Django 5.0.7 on 2024-10-05 22:43

import apps.base.services
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название магазина (максимум 150 символов)', max_length=150, verbose_name='Название магазина')),
                ('description', models.TextField(blank=True, help_text='Введите краткое описание магазина (максимум 350 символов)', max_length=350, null=True, verbose_name='Описание')),
                ('logo', models.ImageField(help_text='Загрузите логотип магазина', upload_to=apps.base.services.path_logo_shop, verbose_name='Логотип')),
                ('background', models.ImageField(blank=True, help_text='Загрузите фон для магазина (опционально)', null=True, upload_to=apps.base.services.path_background_shop, verbose_name='Фон')),
                ('address', models.CharField(help_text='Введите полный адрес магазина', max_length=400, verbose_name='Адрес')),
                ('indicate_address', models.BooleanField(blank=True, default=True, help_text='Укажите, нужно ли показывать адрес магазина', verbose_name='Указать адрес')),
                ('ban', models.BooleanField(blank=True, default=True, help_text='Укажите, заблокирован ли магазин', verbose_name='Бан')),
                ('number_of_complaints', models.PositiveIntegerField(blank=True, default=0, help_text='Количество жалоб, поданных на магазин', verbose_name='Количество жалоб')),
                ('link', models.TextField(blank=True, help_text='Введите ссылку на магазин (опционально)', max_length=250, null=True, verbose_name='Ссылка')),
                ('date_of_created', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания магазина', verbose_name='Дата создания')),
                ('user', models.OneToOneField(help_text='Пользователь, создавший магазин', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_rating', models.PositiveSmallIntegerField(help_text='Оценка магазина от 1 до 5', validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Оценка')),
                ('comment', models.CharField(blank=True, max_length=150, null=True)),
                ('date_writing', models.DateTimeField(auto_now_add=True, help_text='Дата и время написания отзыва', verbose_name='Дата написания')),
                ('update_to', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления отзыва', verbose_name='Дата обновления')),
                ('user', models.OneToOneField(help_text='Пользователь, оставивший оценку', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('shop', models.OneToOneField(help_text='Магазин, который был оценен', on_delete=django.db.models.deletion.CASCADE, to='shops.shop', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Введите текст жалобы (максимум 1000 символов)', max_length=1000, verbose_name='Текст жалобы')),
                ('screenshot', models.ImageField(blank=True, help_text='Загрузите скриншот, подтверждающий жалобу (опционально)', null=True, upload_to=apps.base.services.path_screenshot_complaint, verbose_name='Скриншот')),
                ('date_writing', models.DateTimeField(auto_now_add=True, help_text='Дата и время написания жалобы', verbose_name='Дата написания')),
                ('user', models.ForeignKey(help_text='Пользователь, подавший жалобу', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('shop', models.OneToOneField(help_text='Выберите магазин, на который подана жалоба', on_delete=django.db.models.deletion.PROTECT, to='shops.shop', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Жалоба',
                'verbose_name_plural': 'Жалобы',
            },
        ),
    ]
