# Generated by Django 5.0.7 on 2024-10-14 19:21

import apps.base.services
import apps.base.validators
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Введите текст жалобы (максимум 1000 символов)', max_length=1000, verbose_name='Текст жалобы')),
                ('screenshot', models.ImageField(blank=True, help_text='Загрузите скриншот, подтверждающий жалобу (опционально)', null=True, upload_to=apps.base.services.path_screenshot_complaint, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), apps.base.validators.FileSizeValidator()], verbose_name='Скриншот')),
                ('complaint_processed', models.BooleanField(blank=True, default=False, help_text='Укажите, была ли жалоба обработана', verbose_name='Жалоба обработана')),
                ('date_writing', models.DateTimeField(auto_now_add=True, help_text='Дата и время написания жалобы', verbose_name='Дата написания')),
            ],
            options={
                'verbose_name': 'жалобу',
                'verbose_name_plural': 'жалобы',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_rating', models.PositiveSmallIntegerField(help_text='Оценка магазина от 1 до 5', validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Оценка')),
                ('comment', models.CharField(blank=True, max_length=150, null=True, verbose_name='Комментарии для магазина')),
                ('date_writing', models.DateTimeField(auto_now_add=True, help_text='Дата и время написания отзыва', verbose_name='Дата написания')),
                ('update_to', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления отзыва', verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'рейтинг',
                'verbose_name_plural': 'рейтинги',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название магазина (максимум 150 символов)', max_length=150, verbose_name='Название магазина')),
                ('description', models.TextField(blank=True, help_text='Введите краткое описание магазина (максимум 350 символов)', max_length=350, null=True, verbose_name='Описание')),
                ('logo', models.ImageField(help_text='Загрузите логотип магазина', upload_to=apps.base.services.path_logo_shop, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), apps.base.validators.FileSizeValidator(max_size_mb=1)], verbose_name='Логотип')),
                ('background', models.ImageField(blank=True, help_text='Загрузите фон для магазина (опционально)', null=True, upload_to=apps.base.services.path_background_shop, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), apps.base.validators.FileSizeValidator(max_size_mb=3)], verbose_name='Фон')),
                ('address', models.URLField(help_text='Введите полный адрес магазина (ссылку)', max_length=400, verbose_name='Адрес')),
                ('indicate_address', models.BooleanField(blank=True, default=True, help_text='Укажите, нужно ли отображать адрес магазина', verbose_name='Указать адрес')),
                ('ban', models.BooleanField(blank=True, default=False, help_text='Укажите, заблокировать ли магазин', verbose_name='Бан')),
                ('number_of_complaints', models.PositiveIntegerField(blank=True, default=0, help_text='Количество жалоб, поданных на магазин', verbose_name='Количество жалоб')),
                ('link', models.URLField(blank=True, help_text='Введите ссылку на магазин (опционально)', max_length=250, null=True, verbose_name='Ссылка')),
                ('date_of_created', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания магазина', verbose_name='Дата создания')),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Оценка от 0.00 до 5.00', max_digits=3, validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(0.0)], verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'магазин',
                'verbose_name_plural': 'магазины',
            },
        ),
    ]
