# Generated by Django 5.0.7 on 2024-10-14 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(help_text='Пользователь, подавший жалобу', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(help_text='Пользователь, оставивший оценку', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='shop',
            name='user',
            field=models.OneToOneField(help_text='Пользователь, создавший магазин', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='rating',
            name='shop',
            field=models.ForeignKey(help_text='Магазин, который был оценен', on_delete=django.db.models.deletion.CASCADE, to='shops.shop', verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='shop',
            field=models.ForeignKey(help_text='Выберите магазин, на который подана жалоба', on_delete=django.db.models.deletion.PROTECT, to='shops.shop', verbose_name='Магазин'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'shop')},
        ),
        migrations.AlterUniqueTogether(
            name='complaint',
            unique_together={('user', 'shop')},
        ),
    ]
