# Generated by Django 5.0.7 on 2024-10-06 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='ban',
            field=models.BooleanField(blank=True, default=False, help_text='Укажите, заблокирован ли магазин', verbose_name='Бан'),
        ),
    ]
