# Generated by Django 5.0.7 on 2024-10-06 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_alter_rating_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_processed',
            field=models.BooleanField(blank=True, default=False, help_text='Укажите, была ли жалоба обработана', verbose_name='Жалоба обработана'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(help_text='Введите полный адрес магазина (ссылку)', max_length=400, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='ban',
            field=models.BooleanField(blank=True, default=False, help_text='Укажите, заблокировать ли магазин', verbose_name='Бан'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='indicate_address',
            field=models.BooleanField(blank=True, default=True, help_text='Укажите, нужно ли отображать адрес магазина', verbose_name='Указать адрес'),
        ),
    ]
