# Generated by Django 5.0.7 on 2024-10-06 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_complaint_complaint_processed_alter_shop_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='shop',
            field=models.ForeignKey(help_text='Магазин, который был оценен', on_delete=django.db.models.deletion.CASCADE, to='shops.shop', verbose_name='Магазин'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'shop')},
        ),
    ]
