# Generated by Django 5.0.7 on 2024-10-06 03:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_alter_rating_shop_alter_rating_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='average_rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Оценка от 1 до 5', validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Рейтинг'),
        ),
    ]
