# Generated by Django 5.0.7 on 2024-10-06 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_shop_average_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='shop',
            field=models.ForeignKey(help_text='Выберите магазин, на который подана жалоба', on_delete=django.db.models.deletion.PROTECT, to='shops.shop', verbose_name='Магазин'),
        ),
        migrations.AlterUniqueTogether(
            name='complaint',
            unique_together={('user', 'shop')},
        ),
    ]
