# Generated by Django 5.0.7 on 2024-10-06 03:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_alter_complaint_shop_alter_complaint_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, help_text='Оценка от 1 до 5', max_digits=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Рейтинг'),
        ),
    ]
