# Generated by Django 5.0.7 on 2024-10-06 04:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_alter_shop_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.URLField(help_text='Введите полный адрес магазина (ссылку)', max_length=400, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Оценка от 0.00 до 5.00', max_digits=3, validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(0.0)], verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='link',
            field=models.URLField(blank=True, help_text='Введите ссылку на магазин (опционально)', max_length=250, null=True, verbose_name='Ссылка'),
        ),
    ]
