# Generated by Django 5.0 on 2024-10-07 05:38

import apps.base.services
import apps.base.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_alter_shop_address_alter_shop_average_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='screenshot',
            field=models.ImageField(blank=True, help_text='Загрузите скриншот, подтверждающий жалобу (опционально)', null=True, upload_to=apps.base.services.path_screenshot_complaint, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), apps.base.validators.validate_foto_base], verbose_name='Скриншот'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='background',
            field=models.ImageField(blank=True, help_text='Загрузите фон для магазина (опционально)', null=True, upload_to=apps.base.services.path_background_shop, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), apps.base.validators.validate_foto_base], verbose_name='Фон'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ImageField(help_text='Загрузите логотип магазина', upload_to=apps.base.services.path_logo_shop, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), apps.base.validators.validate_foto_logo_shop], verbose_name='Логотип'),
        ),
    ]
