# Generated by Django 5.0 on 2024-10-08 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0010_alter_complaint_screenshot_alter_shop_background_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'verbose_name': 'жалобу', 'verbose_name_plural': 'жалобы'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'рейтинг', 'verbose_name_plural': 'рейтинги'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'магазин', 'verbose_name_plural': 'магазины'},
        ),
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Комментарии для магазина'),
        ),
    ]
