# Generated by Django 5.0.7 on 2024-11-17 20:12

import apps.base.services
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('icon', models.ImageField(upload_to='icons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png']), apps.base.services.FileSizeValidator(max_size_mb=1)])),
            ],
        ),
        migrations.CreateModel(
            name='FotoProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to=apps.base.services.path_photo_product, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg']), apps.base.services.FileSizeValidator(max_size_mb=1)])),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('currency', models.CharField()),
                ('rating', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=3, validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(0.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('icon', models.ImageField(upload_to='icons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png']), apps.base.services.FileSizeValidator(max_size_mb=1)])),
            ],
        ),
    ]
