# Generated by Django 5.0.7 on 2024-11-17 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ratings', '0001_initial'),
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fotoratingproduct',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.ratingproduct'),
        ),
        migrations.AddField(
            model_name='ratingshop',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop'),
        ),
        migrations.AddField(
            model_name='ratingshop',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='ratingproduct',
            unique_together={('user', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='ratingshop',
            unique_together={('user', 'shop')},
        ),
    ]
